
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIAGONAL = 24;
  public static final int DOSPUNTOS = 32;
  public static final int EXTRA = 13;
  public static final int TIPO = 15;
  public static final int ENTERO = 34;
  public static final int UNIR = 11;
  public static final int CORCHETEC = 28;
  public static final int PIE = 6;
  public static final int PORCENTAJE = 17;
  public static final int CORCHETEA = 27;
  public static final int ETIQUETAS = 9;
  public static final int PUNTOCOMA = 33;
  public static final int ASTERISCO = 23;
  public static final int PARENTESISC = 26;
  public static final int PARENTESISA = 25;
  public static final int EJEY = 8;
  public static final int EJEX = 7;
  public static final int TITULO = 2;
  public static final int EOF = 0;
  public static final int VALORES = 10;
  public static final int PALABRA = 18;
  public static final int error = 1;
  public static final int DIGITO = 35;
  public static final int COMA = 31;
  public static final int COMENTARIO = 3;
  public static final int MENOS = 22;
  public static final int BARRA = 5;
  public static final int TOTAL = 12;
  public static final int PUNTO = 30;
  public static final int CANTIDAD = 16;
  public static final int DEF = 4;
  public static final int TEXTO = 29;
  public static final int LLAVEC = 21;
  public static final int EJECUTAR = 14;
  public static final int LLAVEA = 20;
  public static final int MAS = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TITULO",
  "COMENTARIO",
  "DEF",
  "BARRA",
  "PIE",
  "EJEX",
  "EJEY",
  "ETIQUETAS",
  "VALORES",
  "UNIR",
  "TOTAL",
  "EXTRA",
  "EJECUTAR",
  "TIPO",
  "CANTIDAD",
  "PORCENTAJE",
  "PALABRA",
  "MAS",
  "LLAVEA",
  "LLAVEC",
  "MENOS",
  "ASTERISCO",
  "DIAGONAL",
  "PARENTESISA",
  "PARENTESISC",
  "CORCHETEA",
  "CORCHETEC",
  "TEXTO",
  "PUNTO",
  "COMA",
  "DOSPUNTOS",
  "PUNTOCOMA",
  "ENTERO",
  "DIGITO"
  };
}

